apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3  # 3 replicas as per requirements
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: login-signup-backend:latest
        imagePullPolicy: Never  # Use local image for Minikube
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: jwt-secret
        - name: PORT
          value: "5000"
        - name: EMAIL_SERVICE
          value: "gmail"
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: email-user
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: email-password
        - name: FRONTEND_URL
          value: "http://localhost:3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"