apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3  # 3 replicas as per requirements
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: login-signup-frontend:latest
        imagePullPolicy: Never  # Use local image for Minikube
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: /api  # Will be handled by Nginx ingress or service proxy