apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongo-root-username: cm9vdA==  # root (base64 encoded)
  mongo-root-password: ZXhhbXBsZQ==  # example (base64 encoded)
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=  # your-secret-key-change-this-in-production (base64 encoded)